# Generated by Django 3.2 on 2021-05-07 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_heuaccountinfo_report_daily'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('credit', models.IntegerField()),
                ('total_time', models.IntegerField()),
                ('assessment_method', models.CharField(max_length=100)),
                ('attributes', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('general_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CourseScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heu_username', models.CharField(max_length=100)),
                ('score', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.courseinfo')),
            ],
        ),
    ]
