# Generated by Django 3.2 on 2021-05-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_courseinfo_coursescore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='credit',
            field=models.CharField(max_length=20),
        ),
    ]
