# Generated by Django 3.2 on 2021-05-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_courseinfo_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='course_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='total_time',
            field=models.CharField(max_length=20),
        ),
    ]
