# Generated by Django 3.2 on 2021-05-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210507_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursescore',
            name='term',
            field=models.CharField(default='temp', max_length=50),
            preserve_default=False,
        ),
    ]
