# Generated by Django 3.2 on 2021-05-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_scorequeryresult_timetablequeryresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scorequeryresult',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='timetablequeryresult',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scorequeryresult',
            name='fail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timetablequeryresult',
            name='fail',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scorequeryresult',
            name='result',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='timetablequeryresult',
            name='result',
            field=models.TextField(default=''),
        ),
    ]
