# Generated by Django 3.2 on 2021-05-16 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210516_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseinfo',
            options={'ordering': ('-count',)},
        ),
    ]
