# Generated by Django 3.2 on 2021-06-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_courseinfo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecomment',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
