# Generated by Django 3.2 on 2021-06-04 12:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_coursecomment_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='heuaccountinfo',
            name='first_time_collect_scores',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='RecentGradeCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.courseinfo')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
