# Generated by Django 3.2 on 2021-06-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_heuaccountinfo_first_time_collect_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='heuaccountinfo',
            name='first_time_collect_scores',
            field=models.BooleanField(default=True),
        ),
    ]
