# Generated by Django 3.2 on 2021-06-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_heuaccountinfo_first_time_collect_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='heuaccountinfo',
            name='mail_when_grade',
            field=models.BooleanField(default=False),
        ),
    ]
