# Generated by Django 3.2 on 2021-06-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_heuaccountinfo_mail_when_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heuaccountinfo',
            name='first_time_collect_scores',
        ),
        migrations.AddField(
            model_name='heuaccountinfo',
            name='fail_last_time',
            field=models.BooleanField(default=True),
        ),
    ]
